dailyfresh/apps/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.cart),
    url(r'^add$', views.add),
    url(r'^edit$', views.edit),
    url(r'^delete$', views.delete),
]

dailyfresh/dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('users.urls')),
    url(r'^tinymce', include('tinymce.urls')),
    url(r'^', include('goods.urls')),
    # url(r'^search/', include('haystack.urls')),
    url(r'^cart/', include('cart.urls')),
    url(r"^order/", include('orders.urls')),
]

dailyfresh/apps/cart/models.py
from django.db import models

# Create your models here.

dailyfresh/apps/orders/models.py
from django.db import models
from utils.models import BaseModel
from users.models import User, Address
from goods.models import GoodsSKU

# Create your models here.


class OrderInfo(BaseModel):
    """订单信息"""
    PAY_METHODS = {
        1: "货到付款",
        2: "支付宝",
    }

    PAY_METHODS_ENUM = {
        "CASH": 1,
        "ALIPAY": 2
    }

    PAY_METHOD_CHOICES = (
        (1, "货到付款"),
        (2, "支付宝"),
    )

    ORDER_STATUS = {
        1: "待支付",
        2: "待发货",
        3: "待收货",
        4: "待评价",
        5: "已完成",
    }

    ORDER_STATUS_ENUM = {
        "UNPAID": 1,
        "UNSEND": 2,
        "UNRECEIVED": 3,
        "UNCOMMENT": 4,
        "FINISHED": 5
    }

    ORDER_STATUS_CHOICES = (
        (1, "待支付"),
        (2, "待发货"),
        (3, "待收货"),
        (4, "待评价"),
        (5, "已完成"),
    )

    order_id = models.CharField(max_length=64, primary_key=True, verbose_name="订单号")
    user = models.ForeignKey(User, verbose_name="下单用户")
    address = models.ForeignKey(Address, verbose_name="收获地址")
    total_count = models.IntegerField(default=1, verbose_name="商品总数")
    total_amount = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="商品总金额")
    trans_cost = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="运费")
    pay_method = models.SmallIntegerField(choices=PAY_METHOD_CHOICES, default=1, verbose_name="支付方式")
    status = models.SmallIntegerField(choices=ORDER_STATUS_CHOICES, default=1, verbose_name="订单状态")
    trade_id = models.CharField(max_length=100, unique=True, null=True, blank=True, verbose_name="支付编号")

    class Meta:
        db_table = "df_order_info"


class OrderGoods(BaseModel):
    """订单商品"""
    order = models.ForeignKey(OrderInfo, verbose_name="订单")
    sku = models.ForeignKey(GoodsSKU, verbose_name="订单商品")
    count = models.IntegerField(default=1, verbose_name="数量")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="单价")
    comment = models.TextField(default="", verbose_name="评价信息")

    class Meta:
        db_table = "df_order_goods"

dailyfresh/apps/cart/views.py
from django.shortcuts import render
from django.http import JsonResponse, Http404
from django_redis import get_redis_connection
import json  # 用于字典与字符串之间转换
from goods.models import GoodsSKU

# Create your views here.


def cart(request):
    """购物车"""
    # 购物车列表
    sku_list = []

    # 用户登陆后,从redis读取数据
    if request.user.is_authenticated():
        # 连接数据库
        redis_cli = get_redis_connection()
        key = 'cart%d' % request.user.id
        id_list = redis_cli.hkeys(key)
        for gid in id_list:
            sku = GoodsSKU.objects.get(pk=gid)
            sku.cart_count = int(redis_cli.hget(key, gid))  # 添加一个属性,把数量传递过去
            sku_list.append(sku)
    else:
        # 没有登陆从cookies读取
        cart_str = request.COOKIES.get('cart')
        if cart_str:
            cart_list = json.loads(cart_str)
            for k, v in cart_list.items():
                sku = GoodsSKU.objects.get(pk=k)
                sku.cart_count = v
                sku_list.append(sku)

    context = {
        'title': '购物车',
        'sku_list': sku_list,
    }
    return render(request, 'cart.html', context)


def add(request):
    """购物车添加功能"""
    # Post请求验证
    if request.method != 'POST':
        return Http404()

    # 接收请求,获取sku和数量
    dict = request.POST
    sku_id = dict.get("sku_id", 0)
    count = int(dict.get("count", 0))

    # 后端进行数据验证
    if GoodsSKU.objects.filter(pk=sku_id).count() <= 0:
        return JsonResponse({'status': 2})
    if count <= 0:
        return JsonResponse({'status': 3})

    # 判断用户是否登陆
    if request.user.is_authenticated():
        # 读取cookies信息存储到redis中
        # cart_str = request.GET.get('cart')
        # cart_dict = json.loads(cart_str)
        # 链接数据库
        redis_cli = get_redis_connection()
        key = 'cart%d' % request.user.id

        # 存储字典
        # for k, v in cart_dict.items():
        # 判断是否存在相同商品
        if redis_cli.hexists(key, sku_id):
            count0 = int(redis_cli.hget(key, sku_id))
            count1 = count + count0
            if count1 > 5:
                count1 = 5
            redis_cli.hset(key, sku_id, count1)
        else:
            redis_cli.hset(key, sku_id, count)

        # 获取购物车数量
        total_num = 0
        for num in redis_cli.hvals(key):
            total_num += int(num)

        return JsonResponse({'status': 1, 'count': total_num})

    else:
        # 未登录的情况下保存在cookie中

        # 读取已有cookie数据
        cart_str = request.COOKIES.get('cart')
        if cart_str:
            cart_dict = json.loads(cart_str)
        else:
            cart_dict = {}

        # 获取购物车数量,如果相同,相加
        if sku_id in cart_dict:
            count = cart_dict[sku_id] + count
            # 购物数量限制
            if count > 5:
                count = 5
        # 重构cookies
        cart_dict[sku_id] = count

        # 获取购物车的物品数量
        total_num = 0
        for k, v in cart_dict.items():
            total_num += v

        # 设置新的cookie数据
        cart_str = json.dumps(cart_dict)  # 进行字符串转换
        response = JsonResponse({'status': 1, 'count': total_num})
        response.set_cookie('cart', cart_str, expires=60*60*24*14)

        return response


def edit(request):
    """编辑购物车"""
    # 接收请求
    if request.method != 'POST':
        return Http404()
    # 接收数据
    sku_id = request.POST.get('sku_id')
    count = int(request.POST.get('count'))

    # 后端有效性判断
    if GoodsSKU.objects.filter(pk=sku_id).count() <= 0:
        return JsonResponse({'status': 2})
    if count <= 0:
        count = 1
    elif count >= 5:
        count = 5
    # 构造返回体
    response = JsonResponse({'status': 1})

    # 数据处理
    if request.user.is_authenticated():
        # redis中处理
        redis_cli = get_redis_connection()
        redis_cli.hset('cart%d' % request.user.id, sku_id, count)
        pass
    else:
        # cookies中处理
        cart_str = request.COOKIES.get('cart')
        if cart_str:
            cart_list = json.loads(cart_str)
            cart_list[sku_id] = count
            cart_str = json.dumps(cart_list)
        response.set_cookie('cart', cart_str, expires=60*60*24*14)

    return response


def delete(request):
    """删除购物车"""
    if request.method != 'POST':
        return Http404()
    sku_id = request.POST.get('sku_id')
    response = JsonResponse({'status': 1})
    # redis删除
    if request.user.is_authenticated():
        redis_cli = get_redis_connection()
        redis_cli.hdel('cart%d' % request.user.id, sku_id)
        pass
    else:
        # cookies删除
        cart_str = request.COOKIES.get('cart')
        if cart_str:
            cart_list = json.loads(cart_str)
            cart_list.pop(sku_id)
            cart_str = json.dumps(cart_list)
        response.set_cookie('cart', cart_str, expires=60*60*24*14)

    return response

dailyfresh/templates/base_bottom.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-{{ title }}</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
    {% block head %}
    {% endblock head %}
</head>
<body>
{% block body %}
{% endblock body %}
    <div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
</body>
</html>

dailyfresh/templates/base_goods.html
{% extends 'base_top.html' %}
{% block body1 %}
    <div class="search_bar clearfix">
		<a href="/index" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="search_con fl">
            <form action="/search/" method="get">
			<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			<input type="submit" class="input_btn fr" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="/cart" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ total_count }}</div>
		</div>
	</div>

    {% block body2 %}
    {% endblock body2 %}
{% endblock body1 %}

dailyfresh/templates/base_top.html
{% extends 'base_bottom.html' %}
{% block body %}
    	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {% if request.user.is_authenticated %}
                    <div class="login_btn fl">
					    欢迎您：<em>{{ request.user.username }}</em>
                        <span>|</span>
					    <a href="/users/logout">退出</a>
				    </div>
                {% else %}
                    <div class="login_btn fl">
					    <a href="/users/login">登录</a>
					    <span>|</span>
					    <a href="/users/register">注册</a>
				    </div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="/users/info">用户中心</a>
					<span>|</span>
					<a href="/cart">我的购物车</a>
					<span>|</span>
					<a href="/users/order">我的订单</a>
				</div>
			</div>
		</div>
	</div>
    {% block body1 %}
    {% endblock body1 %}
{% endblock body %}

dailyfresh/templates/base_user.html
{% extends 'base_top.html' %}
{% block body1 %}
    <div class="search_bar clearfix">
		<a href="/index" class="logo fl"><img src="../static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{{ title }}</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
    </div>
    {% block body2 %}
    {% endblock body2 %}
{% endblock body1 %}

dailyfresh/templates/cart.html
{% extends 'base_user.html' %}
{% block head %}
    <script>
        $(function () {
            // 计算小计和总价
            get_total_price();
            // 复选框绑定点击事件
            $(':checkbox:not(#checkall)').click(function () {
                // get_total_price();
                // 获取总价和总数
                var total_price = parseFloat($('.settlements').find('em').text());
                var total_count = parseInt($('.settlements').find('b').text());
                // 获取当前点击的小计和数量
                var price = parseFloat($(this).parent().siblings('.col07').children('em').text());
                var count = parseInt($(this).parent().siblings('.col06').find('.num_show').val());
                if($(this).prop('checked')){
                    total_price += price;
                    total_count +=count;
                }else {
                    total_count -= count;
                    total_price -= price;
                }
                // 重新赋值
                $('.settlements').find('em').text(total_price.toFixed(2));
                $('.settlements').find('b').text(total_count);
                //如有未选中, 多选框取消勾选
                var checkbox_num = $(':checkbox:not(#checkall)').length;
                var checked_num = $(':checked:not(#checkall)').length;
                if (checkbox_num == checked_num){
                    $('#checkall').prop('checked', true);
                }else {
                    $('#checkall').prop('checked', false);
                }
            });
            // 全选框事件
            $('#checkall').click(function () {
                var check = $(this).prop('checked');
                $(':checkbox:not(this)').prop('checked', check);
                get_total_price();
            });
            // 商品数量修改,文本框
            $('.num_show').blur(function () {
                var count = parseInt($(this).val());
                // 数据有效性判断
                if(isNaN(count)){
                    count = 1;
                };
                if(count <=0){
                    count=1;
                    $(this).siblings('.minus').prop('disabled', true)
                }else{
                    $(this).siblings('.minus').prop('disabled', false)
                }
                if(count >=5){
                    count = 5;
                    $(this).siblings('.add').prop('disabled', true)
                }else {
                    $(this).siblings('.add').prop('disabled', false)
                }
                $(this).val(count);
                // 发送post请求
                $.post('/cart/edit', {
                    'sku_id': $(this).parents('.cart_list_td').find(':input:hidden').val(),
                    'count': count,
                    'csrfmiddlewaretoken':'{{ csrf_token }}'
                }, function (data) {
                    if(data.status == 1){
                        //alert(count);
                    };
                });
                get_total_price();
            });
            //+1
            $('.add').click(function () {
                var count = parseInt($(this).siblings('.num_show').val());
                count++;
                $(this).siblings('.num_show').val(count).blur();
            });
            //-1
            $('.minus').click(function () {
                var count = parseInt($(this).siblings('.num_show').val());
                count--;
                $(this).siblings('.num_show').val(count).blur();
            });
            //删除
            $('.col08>a').click(function () {
                var del_ul = $(this).parents('ul');
                if(confirm('确定要删除吗?')){
                    $.post('/cart/delete', {
                        'sku_id': $(this).parents('.cart_list_td').find(':input:hidden').val(),
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                    }, function (data) {
                        if(data.status == 1){
                            del_ul.remove();
                            get_total_price();
                        };
                    });
                };
            });
        });
        // 计算小计和总价,数量
        function get_total_price() {
            var $pay_money = 0;
            var total_count = 0;
            var total_select = 0;
            $('.cart_list_td').each(function (i, n) {

                var $price = parseFloat($(n).find('.col05>em').text());
                var $count = parseInt($(n).find('.num_show').val());
                var $total_price = $price * $count;
                $(n).find('.col07>em').text($total_price.toFixed(2));
                // 购物车没有商品时
                if(!isNaN($count)){
                    total_count += $count;
                };
                // 判断是否勾选
                if ($(n).find('.col01>input').prop('checked')){
                    $pay_money += $total_price;
                    total_select += $count;
                };
            });
            $('.settlements').find('.col03>em').text($pay_money.toFixed(2)); //总价
            $('.settlements').find('b').text(total_select);
            $('.total_count>em').text(total_count);
        }
    </script>
{% endblock head %}
{% block body2 %}
	<div class="total_count">全部商品<em>2</em>件</div>	
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
    <form action="/order/" method="get">
        {% for sku in sku_list %}
        <ul class="cart_list_td clearfix">
            <input type="hidden" value="{{ sku.id }}">
            <li class="col01"><input type="checkbox" name="sku_id" checked="checked" value="{{ sku.id }}"></li>
            <li class="col02"><img src="{{ sku.default_image.url }}"></li>
            <li class="col03">{{ sku.name }}<br><em>库存:{{ sku.stock }}</em></li>
            <li class="col04">{{ sku.unit }}</li>
            <li class="col05"><em>{{ sku.price }}</em>元</li>
            <li class="col06">
                <div class="num_add">
                    <input type="button" href="javascript:;" class="add fl" value="+"></input>
                    <input type="text" class="num_show fl" value="{{ sku.cart_count }}">
                    <input type="button" href="javascript:;" class="minus fl" value="-"></input>
                </div>
            </li>
            <li class="col07"><em></em>元</li>
            <li class="col08"><a href="javascript:;">删除</a></li>
        </ul>
            {% empty %}
            <ul class="cart_list_td clearfix"><span style="font-size: 20px;">暂时没有添加任何商品</span></ul>
        {% endfor %}

        <ul class="settlements">
            <li class="col01"><input type="checkbox" id="checkall" checked="checked"></li>
            <li class="col02">全选</li>
            <li class="col03">合计(不含运费)：<span>¥</span><em></em><br>共计<b>2</b>件商品</li>
            <li class="col04"><input type="submit" value="去结算"></li>
        </ul>
    </form>
{% endblock body2 %}

dailyfresh/templates/detail.html
{% extends 'base_goods.html' %}
{% block body2 %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
                    {% for category in category %}
					<li><a href="/list{{ category.id }}" class="{{ category.logo }}">{{ category.name }}</a></li>
                    {% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="/index">首页</a></li>
				<li class="interval">|</li>
				<li><a href="/">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="/">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ sku.category.name }}</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{{ sku.default_image.url }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ sku.name }}</h3>
			<p>{{ sku.title }}</p>
            <div>
                <em style="font-size: 15px;">规  格：</em>
                {% for other in other_list %}
                    {% if other.id == sku.id %}
                        <span class="show_unit" style="font-size: 15px;color: red;">{{ other.price }}/{{ other.unit }}&nbsp;&nbsp;</span>
                    {% else %}
                        <a href="/detail{{ other.id }}"><span class="show_unit" style="font-size: 15px;">{{ other.price }}/{{ other.unit }}&nbsp;&nbsp;</span></a>
                    {% endif %}
                {% endfor %}
            </div>

			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ sku.price }}</em></span>
				<span class="show_unit">单  位：{{ sku.unit }}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
                    <input type="hidden" id="sku_id" value="{{ sku.id }}">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>	
				</div> 
			</div>
			<div class="total">总价：<em>{{ sku.price }}元</em></div>
			<div class="operate_btn">
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" class="add_cart" id="add_cart">加入购物车</a>				
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for new in new_list %}
					<li>
						<a href="/detail{{ new.id }}"><img src="{{ new.default_image.url }}"></a>
						<h4><a href="#">{{ new.name }}</a></h4>
						<div class="prize">￥{{ new.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
                    <dd>{{ sku.goods.desc|safe }}</dd>
				</dl>
			</div>

		</div>
	</div>

	<div class="add_jump"></div>

	<script type="text/javascript" src="/js/jquery-1.12.2.js"></script>
	<script type="text/javascript">
		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;

		$('#add_cart').click(function(){
		    // 通过post请求发送
            $.post('/cart/add', {
                'sku_id': $('#sku_id').val(),
                'count': $('.num_show').val(),
                'csrfmiddlewaretoken': '{{ csrf_token }}'  //满足csrf验证
            }, function (data) {
                // 根据获取的数据判断
                if (data.status == 1){
                    $(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
                    // 动画函数
                    $(".add_jump").stop().animate({
                            'left': $to_y+7,
                            'top': $to_x+7},
                        "fast", function() {
                            $(".add_jump").fadeOut('slow',function(){
                                // 修改购物车数量
                                $('#show_count').html(data.count);
                            });

                        });

                }else if(data.status == 2){
                    alert('没有此商品');
                }else if(data.status == 3){
                    alert('请输入正确的商品数量');
                }
            });
		});

        // 改变数量计算总价
        $('.num_show').blur(function () {
            var price = parseFloat($('.show_pirze>em').text());
            var num = parseInt($(this).val());
            // 不是数字时
            if (isNaN(num)){
                num = 1;
            };
            // 为负数时
            if (num<1){
                num = 1;
            };
            // 超过上限时
            if (num>5){
                num = 5;
            };
            // 显示到文本框
            $(this).val(num);
            var total_price = price * num;
            $('.total>em').text(total_price.toFixed(2) + '元');
        });

        // 数量加
        $('.add').click(function () {
            var num = parseInt($('.num_show').val());
            num++;
            $('.num_show').val(num).blur();  // 代码触发事件
        });

        // 数量减
        $('.minus').click(function () {
            var num = parseInt($('.num_show').val());
            num--;
            $('.num_show').val(num).blur();
        });
	</script>
{% endblock body2 %}

dailyfresh/templates/user_center_order.html
{% extends 'base_user.html' %}
{% block head %}
    <script>
        $(function () {
            // 计算小计
            $('.order_list_table').each(function (i,n) {
                var total_price = 0;
                $(n).find('.order_goods_list').each(function (f,m) {
                    var price = parseFloat($(m).find('span').text());
                    var count = parseInt($(m).children('.col03').text());
                    var total = price * count;
                    total_price += total;
                });
                $(n).find('label').text(total_price.toFixed(2) + '元');

            });
        });
    </script>
{% endblock head %}
{% block body2 %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/users/info">· 个人信息</a></li>
				<li><a href="#" class="active">· 全部订单</a></li>
				<li><a href="/users/site">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
                {% for order in page %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ order.create_time|date:'Y-m-j H:m:s' }}</li>
					<li class="col02">订单号：{{ order.order_id }}</li>
                    {% if order.status == 1 %}
					    <li class="col02 stress">待支付</li>
                        {% elif order.status == 2 %}
                        <li class="col02 stress">待发货</li>
                        {% elif order.status == 3 %}
                        <li class="col02 stress">待收货</li>
                        {% elif order.status == 4 %}
                        <li class="col02 stress">待评价</li>
                        {% elif order.status == 5 %}
                        <li class="col02 stress">已完成</li>
                    {% endif %}
				</ul>
				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                                {% for goods in order.ordergoods_set.all %}
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="{{ goods.sku.default_image.url }}"></li>
									<li class="col02">{{ goods.sku.name|truncatechars:15 }}<em>{{ goods.sku.price }}元/{{ goods.sku.unit }}\g</em></li>
									<li class="col03">{{ goods.count }}</li>
									<li class="col04"><span>{{ goods.sku.price }}</span>元</li>
								</ul>
                                {% endfor %}

							</td>
							<td width="15%"><label></label></td>
                            {% if order.status == 1 %}
							    <td width="15%">待支付</td>
                            {% elif order.status == 2 %}
                                <td width="15%">待发货</td>
                            {% elif order.status == 2 %}
                                <td width="15%">待收货</td>
                            {% elif order.status == 2 %}
                                <td width="15%">待评价</td>
                            {% elif order.status == 2 %}
                                <td width="15%">已完成</td>
                            {% endif %}
                            {% if order.status == 1 %}
                                <td width="15%"><a href="#" class="oper_btn">去付款</a></td>
                            {% elif order.status == 2 %}
                                <td width="15%"><a href="#" class="oper_btn">等待卖家发货</a></td>
                            {% elif order.status == 2 %}
                                <td width="15%"><a href="#" class="oper_btn">请收货</a></td>
                            {% elif order.status == 2 %}
                                <td width="15%"><a href="#" class="oper_btn">去评价</a></td>
                            {% elif order.status == 2 %}
                                <td width="15%"><a href="#" class="oper_btn">已完成</a></td>
                            {% endif %}
						</tr>
					</tbody>
				</table>
				{% endfor %}

				<div class="pagenation">
                    {% if page.has_previous %}
                    <a href="?pindex=1">首页</a>
					<a href="?pindex={{ page.number|add:-1 }}"><上一页</a>
                    {% else %}
                    <a>首页</a>
                    <a>下一页</a>
                    {% endif %}
                    {% for page_num in page_list %}
                        {% if page_num == page.number %}
					        <a href="?pindex={{ page_num}}" class="active">{{ page_num }}</a>
                        {% else %}
                            <a href="?pindex={{ page_num }}">{{ page_num }}</a>
                        {% endif %}
                    {% endfor %}
                    {% if page.has_next %}
					<a href="?pindex={{ page.number|add:1 }}">下一页></a>
                    <a href="?pindex={{ page.paginator.num_pages }}">末页</a>
                    {% endif %}
				</div>
		</div>
	</div>
{% endblock body2 %}

